export const types = {
    LOGIN: 'LOGIN',
    REGISTER: 'REGISTER',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    ME: 'ME',
    UPDATE_ME: 'UPDATE_ME',
    UPDATE_PHOTO: 'UPDATE_PHOTO',
    LOGOUT: 'LOGOUT',
    RESET_PASSWORD: 'RESET_PASSWORD',
    RECOVER_PASSWORD: 'RECOVER_PASSWORD'
};