export const types = {
    FETCH_CIRCULARES: 'FETCH_CIRCULARES',
    FETCH_CIRCULAR_SELECTOR: 'FETCH_CIRCULAR_SELECTOR',
    FETCH_CIRCULAR: 'FETCH_CIRCULAR',
    CREATE_CIRCULAR: 'CREATE_CIRCULAR',
    UPDATE_CIRCULAR: 'UPDATE_CIRCULAR',
    DELETE_CIRCULAR: 'DELETE_CIRCULAR',

    FETCH_CIRCULAR_TAGS: 'FETCH_CIRCULAR_TAGS'
};