<?php

use Illuminate\Database\Seeder;
use App\Fracao;

class FracaoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $items = [
            //---------------------------------------------------BLOCO A
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 1,
                "nome" => "A",
                "piso" => "R/C",
                "tipo" => "T3",
                "area" => 125.35,
                "permilagem" => 18.40,
                "estacionamento" => 29,
                "arrecadação" => 48,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 1,
                "nome" => "B",
                "piso" => "R/C",
                "tipo" => "T2",
                "arrecadação" => 66,
                "estacionamento" => 36,
                "area" => 98.70,
                "permilagem" => 14.40,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 1,
                "nome" => "C",
                "piso" => "R/C",
                "tipo" => "T1",
                "arrecadação" => 63,
                "estacionamento" => 40,
                "area" => 80.85,
                "permilagem" => 11.80,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 1,
                "nome" => "D",
                "piso" => "R/C",
                "tipo" => "T2",
                "arrecadação" => 58,
                "estacionamento" => 32,
                "area" => 97.35,
                "permilagem" => 14.20,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 1,
                "nome" => "E",
                "piso" => "R/C",
                "tipo" => "T2",
                "arrecadação" => 49,
                "estacionamento" => 49,
                "area" => 103.35,
                "permilagem" => 15.10,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 1,
                "nome" => "F",
                "piso" => "1º",
                "tipo" => "T3",
                "arrecadação" => 44,
                "estacionamento" => 25,
                "area" => 125.35,
                "permilagem" => 18.40,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 1,
                "nome" => "G",
                "piso" => "1º",
                "tipo" => "T2",
                "arrecadação" => 65,
                "estacionamento" => 35,
                "area" => 97.85,
                "permilagem" => 14.30,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 1,
                "nome" => "H",
                "piso" => "1º",
                "tipo" => "T1",
                "arrecadação" => 62,
                "estacionamento" => 41,
                "area" => 80.85,
                "permilagem" => 11.80,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 1,
                "nome" => "I",
                "piso" => "1º",
                "tipo" => "T2",
                "arrecadação" => 52,
                "estacionamento" => 45,
                "area" => 97.35,
                "permilagem" => 14.20,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 1,
                "nome" => "J",
                "piso" => "1º",
                "tipo" => "T2",
                "arrecadação" => 54,
                "estacionamento" => 48,
                "area" => 103.35,
                "permilagem" => 15.10,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 1,
                "nome" => "K",
                "piso" => "2º",
                "tipo" => "T3",
                "arrecadação" => 45,
                "estacionamento" => 26,
                "area" => 125.35,
                "permilagem" => 18.40,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 1,
                "nome" => "L",
                "piso" => "2º",
                "tipo" => "T2",
                "arrecadação" => 64,
                "estacionamento" => 34,
                "area" => 97.85,
                "permilagem" => 14.30,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 1,
                "nome" => "M",
                "piso" => "2º",
                "tipo" => "T1",
                "arrecadação" => 61,
                "estacionamento" => 42,
                "area" => 80.85,
                "permilagem" => 11.80,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 1,
                "nome" => "N",
                "piso" => "2º",
                "tipo" => "T2",
                "arrecadação" => 53,
                "estacionamento" => 30,
                "area" => 97.35,
                "permilagem" => 14.30,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 1,
                "nome" => "O",
                "piso" => "2º",
                "tipo" => "T2",
                "arrecadação" => 55,
                "estacionamento" => 47,
                "area" => 103.35,
                "permilagem" => 15.10,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 1,
                "nome" => "P",
                "piso" => "3º",
                "tipo" => "T3",
                "arrecadação" => 46,
                "estacionamento" => 27,
                "area" => 125.35,
                "permilagem" => 18.40,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 1,
                "nome" => "Q",
                "piso" => "3º",
                "tipo" => "T2",
                "arrecadação" => 60,
                "estacionamento" => 33,
                "area" => 97.85,
                "permilagem" => 14.30,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 1,
                "nome" => "R",
                "piso" => "3º",
                "tipo" => "T1",
                "arrecadação" => 59,
                "estacionamento" => 44,
                "area" => 80.85,
                "permilagem" => 11.80,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 1,
                "nome" => "S",
                "piso" => "3º",
                "tipo" => "T2",
                "arrecadação" => 56,
                "estacionamento" => 31,
                "area" => 97.35,
                "permilagem" => 14.20,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 1,
                "nome" => "T",
                "piso" => "3º",
                "tipo" => "T2",
                "arrecadação" => 57,
                "estacionamento" => 46,
                "area" => 103.35,
                "permilagem" => 15.10,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 1,
                "nome" => "U",
                "piso" => "4º",
                "tipo" => "T2",
                "arrecadação" => 68,
                "estacionamento" => 37,
                "area" => 125.85,
                "permilagem" => 18.40,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 1,
                "nome" => "V",
                "piso" => "4º",
                "tipo" => "T3",
                "arrecadação" => 47,
                "estacionamento" => 28,
                "area" => 148.35,
                "permilagem" => 21.80,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 1,
                "nome" => "W",
                "piso" => "4º",
                "tipo" => "T2",
                "arrecadação" => 67,
                "estacionamento" => 39,
                "area" => 124.20,
                "permilagem" => 18.20,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 1,
                "nome" => "X",
                "piso" => "4º",
                "tipo" => "T2",
                "arrecadação" => 43,
                "estacionamento" => 43,
                "area" => 103.85,
                "permilagem" => 15.20,
            ],

            //---------------------------------------------------BLOCO B
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 2,
                "nome" => "Y",
                "piso" => "R/C",
                "tipo" => "T2",
                "arrecadação" => 40,
                "estacionamento" => 22,
                "area" => 103.30,
                "permilagem" => 15.10,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 2,
                "nome" => "Z",
                "piso" => "R/C",
                "tipo" => "T2",
                "arrecadação" => 22,
                "estacionamento" => 15,
                "area" => 97.50,
                "permilagem" => 14.30,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 2,
                "nome" => "AA",
                "piso" => "R/C",
                "tipo" => "T1",
                "arrecadação" => 51,
                "estacionamento" => 50,
                "area" => 80.85,
                "permilagem" => 11.80,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 2,
                "nome" => "AB",
                "piso" => "R/C",
                "tipo" => "T2",
                "arrecadação" => 34,
                "estacionamento" => 54,
                "area" => 97.40,
                "permilagem" => 14.30,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 2,
                "nome" => "AC",
                "piso" => "R/C",
                "tipo" => "T2",
                "arrecadação" => 21,
                "estacionamento" => 14,
                "area" => 103.50,
                "permilagem" => 15.10,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 2,
                "nome" => "AD",
                "piso" => "1º",
                "tipo" => "T2",
                "arrecadação" => 39,
                "estacionamento" => 21,
                "area" => 103.30,
                "permilagem" => 15.10,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 2,
                "nome" => "AE",
                "piso" => "1º",
                "tipo" => "T2",
                "arrecadação" => 23,
                "estacionamento" => 16,
                "area" => 97.50,
                "permilagem" => 14.30,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 2,
                "nome" => "AF",
                "piso" => "1º",
                "tipo" => "T1",
                "arrecadação" => 50,
                "estacionamento" => 51,
                "area" => 80.85,
                "permilagem" => 11.80,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 2,
                "nome" => "AG",
                "piso" => "1º",
                "tipo" => "T2",
                "arrecadação" => 33,
                "estacionamento" => 55,
                "area" => 97.40,
                "permilagem" => 14.30,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 2,
                "nome" => "AH",
                "piso" => "1º",
                "tipo" => "T2",
                "arrecadação" => 26,
                "estacionamento" => 62,
                "area" => 103.40,
                "permilagem" => 15.10,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 2,
                "nome" => "AI",
                "piso" => "2º",
                "tipo" => "T2",
                "arrecadação" => 38,
                "estacionamento" => 20,
                "area" => 103.30,
                "permilagem" => 15.10,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 2,
                "nome" => "AJ",
                "piso" => "2º",
                "tipo" => "T2",
                "arrecadação" => 24,
                "estacionamento" => 17,
                "area" => 97.50,
                "permilagem" => 14.30,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 2,
                "nome" => "AK",
                "piso" => "2º",
                "tipo" => "T1",
                "arrecadação" => 36,
                "estacionamento" => 52,
                "area" => 80.90,
                "permilagem" => 11.80,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 2,
                "nome" => "AL",
                "piso" => "2º",
                "tipo" => "T2",
                "arrecadação" => 32,
                "estacionamento" => 56,
                "area" => 97.40,
                "permilagem" => 14.30,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 2,
                "nome" => "AM",
                "piso" => "2º",
                "tipo" => "T2",
                "arrecadação" => 27,
                "estacionamento" => 61,
                "area" => 103.40,
                "permilagem" => 15.10,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 2,
                "nome" => "AN",
                "piso" => "3º",
                "tipo" => "T2",
                "arrecadação" => 37,
                "estacionamento" => 19,
                "area" => 103.30,
                "permilagem" => 15.10,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 2,
                "nome" => "AO",
                "piso" => "3º",
                "tipo" => "T2",
                "arrecadação" => 30,
                "estacionamento" => 18,
                "area" => 97.40,
                "permilagem" => 14.30,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 2,
                "nome" => "AP",
                "piso" => "3º",
                "tipo" => "T1",
                "arrecadação" => 35,
                "estacionamento" => 53,
                "area" => 80.90,
                "permilagem" => 11.80,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 2,
                "nome" => "AQ",
                "piso" => "3º",
                "tipo" => "T2",
                "arrecadação" => 31,
                "estacionamento" => 57,
                "area" => 97.40,
                "permilagem" => 14.30,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 2,
                "nome" => "AR",
                "piso" => "3º",
                "tipo" => "T2",
                "arrecadação" => 28,
                "estacionamento" => 60,
                "area" => 103.40,
                "permilagem" => 15.10,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 2,
                "nome" => "AS",
                "piso" => "4º",
                "tipo" => "T2",
                "arrecadação" => 42,
                "estacionamento" => 24,
                "area" => 103.30,
                "permilagem" => 15.10,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 2,
                "nome" => "AT",
                "piso" => "4º",
                "tipo" => "T3",
                "arrecadação" => 29,
                "estacionamento" => 59,
                "area" => 123.90,
                "permilagem" => 18.10,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 2,
                "nome" => "AU",
                "piso" => "4º",
                "tipo" => "T3",
                "arrecadação" => 41,
                "estacionamento" => 23,
                "area" => 148.30,
                "permilagem" => 21.80,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 2,
                "nome" => "AV",
                "piso" => "4º",
                "tipo" => "T2",
                "arrecadação" => 25,
                "estacionamento" => 58,
                "area" => 104.20,
                "permilagem" => 15.20,
            ],

            //---------------------------------------------------BLOCO C
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 3,
                "nome" => "AW",
                "piso" => "R/C",
                "tipo" => "T2",
                "arrecadação" => 16,
                "estacionamento" => 9,
                "area" => 102.50,
                "permilagem" => 15.00,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 3,
                "nome" => "AX",
                "piso" => "R/C",
                "tipo" => "T1",
                "arrecadação" => 10,
                "estacionamento" => 63,
                "area" => 72.15,
                "permilagem" => 10.60,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 3,
                "nome" => "AY",
                "piso" => "R/C",
                "tipo" => "T2",
                "arrecadação" => 20,
                "estacionamento" => 13,
                "area" => 84.30,
                "permilagem" => 12.30,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 3,
                "nome" => "AZ",
                "piso" => "R/C",
                "tipo" => "T3",
                "arrecadação" => 1,
                "estacionamento" => 1,
                "area" => 121.65,
                "permilagem" => 17.80,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 3,
                "nome" => "BA",
                "piso" => "1º",
                "tipo" => "T2",
                "arrecadação" => 15,
                "estacionamento" => 8,
                "area" => 102.50,
                "permilagem" => 15.00,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 3,
                "nome" => "BB",
                "piso" => "1º",
                "tipo" => "T1",
                "arrecadação" => 9,
                "estacionamento" => 64,
                "area" => 72.15,
                "permilagem" => 10.60,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 3,
                "nome" => "BC",
                "piso" => "1º",
                "tipo" => "T2",
                "arrecadação" => 19,
                "estacionamento" => 12,
                "area" => 83.50,
                "permilagem" => 12.30,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 3,
                "nome" => "BD",
                "piso" => "1º",
                "tipo" => "T3",
                "arrecadação" => 2,
                "estacionamento" => 2,
                "area" => 121.65,
                "permilagem" => 17.80,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 3,
                "nome" => "BE",
                "piso" => "2º",
                "tipo" => "T2",
                "arrecadação" => 11,
                "estacionamento" => 67,
                "area" => 102.65,
                "permilagem" => 15.00,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 3,
                "nome" => "BF",
                "piso" => "2º",
                "tipo" => "T1",
                "arrecadação" => 8,
                "estacionamento" => 65,
                "area" => 72.15,
                "permilagem" => 10.60,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 3,
                "nome" => "BG",
                "piso" => "2º",
                "tipo" => "T2",
                "arrecadação" => 18,
                "estacionamento" => 11,
                "area" => 83.50,
                "permilagem" => 12.30,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 3,
                "nome" => "BH",
                "piso" => "2º",
                "tipo" => "T3",
                "arrecadação" => 3,
                "estacionamento" => 3,
                "area" => 121.65,
                "permilagem" => 17.80,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 3,
                "nome" => "BI",
                "piso" => "3º",
                "tipo" => "T2",
                "arrecadação" => 13,
                "estacionamento" => 68,
                "area" => 102.80,
                "permilagem" => 15.00,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 3,
                "nome" => "BJ",
                "piso" => "3º",
                "tipo" => "T1",
                "arrecadação" => 7,
                "estacionamento" => 66,
                "area" => 72.15,
                "permilagem" => 10.60,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 3,
                "nome" => "BK",
                "piso" => "3º",
                "tipo" => "T2",
                "arrecadação" => 17,
                "estacionamento" => 10,
                "area" => 83.50,
                "permilagem" => 12.30,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 3,
                "nome" => "BL",
                "piso" => "3º",
                "tipo" => "T3",
                "arrecadação" => 4,
                "estacionamento" => 4,
                "area" => 121.65,
                "permilagem" => 17.80,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 3,
                "nome" => "BM",
                "piso" => "4º",
                "tipo" => "T3",
                "arrecadação" => 5,
                "estacionamento" => 5,
                "area" => 152.30,
                "permilagem" => 22.44,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 3,
                "nome" => "BN",
                "piso" => "4º",
                "tipo" => "T1",
                "arrecadação" => 14,
                "estacionamento" => 7,
                "area" => 89.30,
                "permilagem" => 13.10,
            ],
            [
                "fracao_estado_id" => 1,
                "bloco_id" => 3,
                "nome" => "BO",
                "piso" => "4º",
                "tipo" => "T2",
                "arrecadação" => 12,
                "estacionamento" => 6,
                "area" => 140.40,
                "permilagem" => 20.50,
            ],
        ];

        foreach ($items as $item) {
            Fracao::Create($item);
        }
    }
}
