<?php

use App\Pergunta;
use Illuminate\Database\Seeder;

class PerguntaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $items = [
            ['question' => 'Quais as funções do administrador ?', 'answer' => 'Convocar a assembleia de condóminos; Elaborar os orçamentos anuais de receitas e despesas e prestar contas à assembleia; Cobrar as receitas e efectuar as despesas comuns; Exigir dos condóminos a sua quota-parte nas despesas aprovadas pela assembleia; Providenciar duas contas bancárias do condomínio: uma para as contas correntes e outra para o fundo comum de reserva; Executar as deliberações da assembleia; Realizar as reparações no prédio e outros actos necessários à sua conservação; Regular o uso das coisas comuns e a prestação dos serviços de interesse comum; Representar o condomínio perante as autoridades administrativas e acções judiciais; Verificar a existência do seguro contra o risco de incêndio; Assegurar a execução do regulamento e das disposições legais e administrativas do condomínio; Transmitir aos condóminos as notificações recebidas das autoridades administrativas; Comunicar aos condóminos não-residentes todos os factos relevantes da vida do condomínio.', 'pergunta_tipo_id' => 1],
            ['question' => 'Que livros deve ter a administração ?', 'answer' => 'Livro de actas; Livro de inventário das coisas comuns; Livro de Receitas/Despesas; Livro para registo da correspondência recebida e enviada.', 'pergunta_tipo_id' => 1],
            ['question' => 'Quem pode ser administrador ?', 'answer' => 'Qualquer condómino; Um terceiro contratado pela assembleia de condóminos; Uma empresa contratada pela assembleia de condóminos.', 'pergunta_tipo_id' => 1],
            ['question' => 'Negligências do Administrador', 'answer' => 'O Administrador (empresa que nomearam) pode ser responsabilizado civilmente, quer por negligência, quer por abuso de confiança.', 'pergunta_tipo_id' => 1],
            ['question' => 'Competências da Administração - Acções Judiciais - Legitimidade', 'answer' => 'O administrador terá competências próprias, como por exemplo cobrar, e exigir o pagamento... Mas, sobre outros assuntos, carece de autorização da assembleia, a menos que a função lhe tenha sido atribuida por via do regulamento do condominio. ', 'pergunta_tipo_id' => 1],

            ['question' => 'Como obter o número de contribuinte do condomínio ?', 'answer' => 'É comprar o impresso que existe nas conservatórias do Registo Comercial, e depois ir ao Registo Nacional de Pessoas Colectivas e pedir um cartão de identificação de entidade equiparada a pessoa colectiva.', 'pergunta_tipo_id' => 2],
            ['question' => 'Poderá o regulamento do condomínio, proibir a existência de animais domésticos nas várias fracções ?', 'answer' => 'Vai ter de pedir o auxílio da Polícia e dos Tribunais se tal for necessário. O Administrador pouco pode fazer.', 'pergunta_tipo_id' => 2],
            ['question' => 'O regulamento pode proibir algumas obras de inovação, isto é, pode proibir a realização de certas obras que não são essenciais para o prédio ?', 'answer' => 'Pode, uma vez que os condóminos podem deliberar em assembleia, por maioria de 2/3, a realização de obras de inovação, também podem criar um documento que previamente determine que algumas obras de inovação são proibidas.', 'pergunta_tipo_id' => 2],
            ['question' => 'Como calcular o valor das quotas ?', 'answer' => 'As despesas correntes de condomínio devem ser pagas pelos condóminos na proporção do valor (permilagem) das suas fracções. Quota mensal = (Orçamento anual/12) * (Permilagem da fracção / 1000)', 'pergunta_tipo_id' => 2],
            ['question' => 'Que tipo de seguro se deve fazer para o condomínio.', 'answer' => 'Segundo a lei, o seguro obrigatório para quem compra um fracção autónoma, é o de incêndio. Mas como as seguradoras oferecem um tipo de seguro chamado multi-riscos, e geralmente é mais barato que o primeiro, uma vez que abrange o conjunto dos condóminos, este último (multi-riscos) é preferível, até porque não se fica pela mera cobertura de risco de incêndio. Há no entanto que ficar atento a algumas exclusões neste tipo de seguros que devem ser avaliadas cuidadosamente, e se possível incluídas.', 'pergunta_tipo_id' => 2],
            ['question' => 'Cálculo da permilagem', 'answer' => 'O cálculo da permilagem de cada fracção torna-se necessário para efeito de conhecer qual a comparticipação nas despesas comuns que compete ao proprietário de cada fracção imobiliária. Esse valor é expresso em percentagem ou permilagem do valor total do imóvel. Regra geral, o valor da permilagem é obtido através do título constitutivo do regime da propriedade horizontal. Ou seja: se as fracções imobiliárias que integram o imóvel foram vendidas a proprietários diversos, houve que constituir previamente, no imóvel, o regime da propriedade horizontal, regime cuja constituição é feita por escritura pública após vistoria camarária.', 'pergunta_tipo_id' => 2],

            ['question' => 'Qual o número de reuniões da assembleia por ano ?', 'answer' => 'Deverá haver uma reunião na primeira quinzena do mês de Janeiro. A reunião é convocada pelo administrador com vista à discussão e aprovação das contas do último ano e aprovação do orçamento para o ano corrente. A data da reunião pode ser alterada, quer através do título constitutivo, quer por acordo unânime entre todos os condóminos. A lei determina que podem existir reuniões extraordinárias sempre que convocadas pelo administrador ou por condóminos que representem 25% do valor do prédio.', 'pergunta_tipo_id' => 3],
            ['question' => 'Composição, Assinatura e Guarda das Actas da Assembleia de Condóminos', 'answer' => 'O condómino que tenha tomado parte na assembleia de condóminos e, podendo fazê-lo (não estando impedido de assinar!), recuse assinar a acta, consignada no respectivo livro ou em folhas soltas, devidamente numeradas e rubricadas, deve ser judicialmente notificado para que assine a acta em prazo não inferior a oito ( dias; decorrido esse prazo, a acta tem a força probatória referida no artigo 1.º, n.º 2, do Decreto-Lei n.º 268/94, de 25 de Outubro, desde que esteja assinada pela maioria dos condóminos que tomaram parte na assembleia de condóminos. O condómino (obstinado em não assinar) notificado judicialmente pode invocar (justificando e provando!) em juízo a falsidade da acta. (cf. artigo 63.º, n.º 3, do Código das Sociedades Comerciais, conjugado com o artigo 1.º, n.º 1, do Decreto-Lei n.º 268/94, de 25 de Outubro). A recusa injustificada da assinatura da acta é punível com sanção de multa até 120 dias. (cf. art.º 521.º do Código Comercial). As actas devem ser lavradas no respectivo livro ou em folhas soltas, devidamente numeradas e rubricadas; no livro ou nas folhas devem ser também consignadas, pela forma estabelecida na lei, as deliberações tomadas em reunião da assembleia de condóminos. Quando essas deliberações constem de escritura pública (título constitutivo da propriedade horizontal, por exemplo) ou de instrumento fora das notas (regulamento do condomínio, por exemplo), deve a administração, o administrador do condomínio, o presidente da reunião ou o secretário inscrever no livro ou nas folhas menção da sua existência. O administrador do condomínio guarda o livro de actas e / ou todas as folhas; as folhas devem ser encadernadas depois de utilizadas e podem, decorridos 10 exercícios após aquele a que se reportam, ser substituídas por microfilmes ou por outra forma adequada de suporte (informático, digital, etc.). Sempre que as actas sejam registadas em folhas soltas, deve a administração tomar as precauções e as medidas necessárias para impedir a sua falsificação. (cf. artigo 63.º, n.ºs 4, 5, 6 e 10, do Código das Sociedades Comerciais, conjugado com os artigos 1430.º, n.º 1 e 1436.º, alínea m), ambos do Código Civil, com o artigo 1.º, n.º 3, do Decreto-Lei n.º 268/94, de 25 de Outubro, e com o artigo 24.º, n.º 4, do Decreto-Lei n.º 135/1999, de 22 de Abril).', 'pergunta_tipo_id' => 3],
            ['question' => 'Aprovação de Documentos', 'answer' => 'A aprovação de obra inovadora em parte comum do prédio sujeito ao regime da propriedade horizontal deve preceder a realização da obra. A aprovação de obra inovadora apenas pode ser dada através de deliberação tomada em assembleia de condóminos, não sendo válida a aprovação obtida fora da assembleia, designadamente através de voto constante de documento escrito. A demolição é a sanção correspondente à realização de obras ofensivas das regras da propriedade horizontal. A simples inacção ou abstenção, mais ou menos longa, desacompanhada de actos geradores de confiança na contraparte, não é de molde a justificar a paralisação do exercício do direito com base no seu exercício abusivo. ', 'pergunta_tipo_id' => 3],
            ['question' => 'Quem pode convocar a reunião da assembleia de condóminos?', 'answer' => 'O administrador do condomínio (cfr. Art.º 1431.º, n.º 1 e 2, conjugado com o art.º 1436.º, alínea a), ambos do Código Civil); Condóminos que representem, pelo menos, 25% do capital investido (isto é, 25 votos, em percentagem, ou 250 votos, em permilagem) (cfr. Art.º 1431.º, n.º 2, conjugado com o art.º 1418.º, n.º 1, e 1430.º, n.º 2, todos do Código Civil); Em determinadas circunstâncias, um único condómino, que pretenda recorrer dos actos do administrador (cfr. Art.º 1438.º, do Código Civil).', 'pergunta_tipo_id' => 3],
            ['question' => 'Qual é a forma legal da convocatória para a reunião da assembleia de condóminos?', 'answer' => 'Carta registada (cfr. Art.º 1432.º, n.º 1, do Código Civil); Aviso convocatório (cfr. Art.º 1432.º, n.º 1, do Código Civil).', 'pergunta_tipo_id' => 3],
            ['question' => 'Qual é a antecedência mínima da convocatória para a reunião da assembleia de condóminos?', 'answer' => 'A convocatória para a reunião da assembleia de condominos deve ser ENVIADA ou ENTREGUE PESSOALMENTE PELO ADMINISTRADOR com a ANTECEDÊNCIA MÍNIMA DE DEZ (10) DIAS em relação a data prevista para a realização da reunião da assembleia de condóminos, não relevando, no caso de envio pelo correio, a data da recepção (entrega ao destinatário da carta-convocatória), mas tão somente a data do seu depósito nos correios (data do registo), não se contando o dia da entrega (registo nos correios ou entrega pessoal) nem o dia da realização da reunião.', 'pergunta_tipo_id' => 3],
            ['question' => 'Qual deve ser o conteúdo da convocatória para a reunião da assembleia de condóminos?', 'answer' => 'Dia da reunião; Hora da reunião; Local da reunião (portaria do prédio, casa ou escritório de um condómino ou do administrador, sala de condóminos, qualquer local privado / reservado dentro da localidade onde o prédio se situa); Ordem de trabalhos da reunião (assuntos ou matérias a tratar na reunião); Assuntos cujas deliberações só podem ser aprovadas por unanimidade dos votos (v. g. alteração do título constitutivo da propriedade horizontal, cfr. Art.º 1419.º, n.ºs 1 e 2, do Código Civil).', 'pergunta_tipo_id' => 3],
            ['question' => 'Quem deve ser convocado para a reunião da assembleia de condóminos?', 'answer' => 'Todos os condóminos devem ser convocados, seja qual for a sua residência, no Pais ou no Estrangeiro.', 'pergunta_tipo_id' => 3],
            ['question' => 'O que fazer então na falta de quorum?', 'answer' => 'Poderá ter sido logo fixada outra data na convocatória (“prolongamento da 1.ª chamada”...). A lei não estabelece nenhum intervalo mínimo obrigatório entre as duas reuniões, nem exige nova convocação dos condóminos faltosos. Caso não tenha sido logo fixada outra data na convocatória (“prolongamento da 1.ª chamada”...), presumir-se-a convocada nova reunião para UMA SEMANA DEPOIS, há mesma hora e no mesmo local. (cfr. Art.º 1432.º, n.º 4, do Código Civil).', 'pergunta_tipo_id' => 3],
            ['question' => 'Como posso impugnar uma assembleia?', 'answer' => 'Deverá verificar os pontos anteriores, nomeadamente: Qual é a forma legal da convocatória para a reunião da assembleia de condóminos; Qual é a antecedência mínima da convocatória para a reunião da assembleia de condóminos; Qual deve ser o conteúdo da convocatória para a reunião da assembleia de condóminos; Quem deve ser convocado para a reunião da assembleia de condóminos...', 'pergunta_tipo_id' => 3],
            ['question' => 'Decisões da Assembleia - Que Maiorias?', 'answer' => 'As deliberações são tomadas, salvo disposição especial, por maioria dos votos representativos do capital investido. Se não comparecer o número de condóminos suficiente para se obter vencimento e na convocatória não tiver sido desde logo fixada outra data, considera-se convocada nova reunião para uma semana depois, na mesma hora e local, podendo neste caso a assembleia deliberar por maioria de votos dos condóminos presentes, desde que estes representem, pelo menos, um quarto do valor total do prédio. As deliberações que careçam de ser aprovadas por unanimidade dos votos podem ser aprovadas por unanimidade dos condóminos presentes desde que estes representem, pelo menos, dois terços do capital investido, sob condição de aprovação da deliberação pelos condóminos ausentes.', 'pergunta_tipo_id' => 3],
            ['question' => 'Que casos a aprovação do Regulamento do Condomínio poderá Não Carecer de Unanimidade?', 'answer' => 'Se (nos casos em que) a escritura pública de constituição de propriedade horizontal (título constitutivo da propriedade horizontal) não contiver o regulamento do condomínio, o regulamento do condomínio pode (e deve, cfr. artigo 1429.º-A, do Código Civil) ser aprovado de acordo com as maiorias deliberativas (Quorum Deliberativo) exigíveis legalmente à assembleia de condóminos, de acordo com as diversas matérias que vise regulamentar (obviamente que devera somente conter matérias que não exijam deliberação por unanimidade!).', 'pergunta_tipo_id' => 3],
            ['question' => 'Actas / Valor Probatório', 'answer' => 'O art. 1432 do Código Civil não refere ao modo de documentar as ocorrências verificadas nas assembleias de condóminos e as respectivas deliberações ao contrário do que, quanto às assembleias das sociedades comerciais, prescreve hoje o art. 63 do CSC e, antes, prescrevia o art. 183 do C. Comercial. A "acta" é apenas um documento escrito que "a posteriori" reproduz o que se passou na reunião dos condóminos, não constituindo um documento negocial "ad substantiam" nem "ad probationem", pois, a sua falta não produz a nulidade da deliberação e a sua existência não impede que contra ela se admita qualquer prova em contrário. A força probatória da acta é apreciada livremente pelo Tribunal - art. 396 do Código Civil - enquanto documento particular informativo testemunhal. A falta de data constitui apenas simples irregularidade da acta, susceptível unicamente de reduzir o seu grau de credibilidade. ', 'pergunta_tipo_id' => 3],

            ['question' => 'O que é o fundo comum de reserva e a conta poupança condomínio ?', 'answer' => ' Este fundo, de constituição obrigatória, é formado por contribuições de cada condómino, para além dos encargos correntes de condomínio, em montante não inferior a 10% da sua quota-parte naqueles encargos e destina-se a custear despesas de conservação do prédio. O montante do fundo será depositado em instituição bancária, podendo ser aplicado numa conta poupança condomínio sob a forma de depósito a prazo com duração mínima de 1 ano, renovável, se a assembleia de condóminos assim o determinar. O saldo desta conta só poder ser aplicado na realização de obras de conservação ordinária ou extraordinária e de beneficiação, nas partes comuns do prédio, e garante a concessão de empréstimos ao condomínio titular da conta poupança condomínio com duração de pelo menos 3 anos. As instituições bancárias devem ter fixadas as condições destas contas, nomeadamente no que concerne ao valor e periodicidade das entregas, à relação entre o montante de empréstimo e o saldo da conta, bem como as taxas de remuneração em vigor.', 'pergunta_tipo_id' => 4],
            ['question' => 'Quem tem poderes para abrir uma conta poupança condomínio ?', 'answer' => 'O administrador do prédio, depois da assembleia de condóminos ter deliberado a aprovação por maioria simples.', 'pergunta_tipo_id' => 4],
            ['question' => 'Animais nas fracções', 'answer' => 'Nas zonas urbanas, por cada fracção autónoma, não é permitido alojar mais de 3 cães adultos. A permanência de cães em habitações situadas em zonas urbanas fica condicionada à existência de boas condições de alojamento dos referidos animais, de ausência de riscos sanitários e inexistência nesses animais de doenças transmissíveis ao homem. As Câmaras Municipais poderão determinar a remoção de quaisquer cães, sempre que razões de salubridade ou tranquilidade da vizinhança o imponham.', 'pergunta_tipo_id' => 4],
            ['question' => 'Infiltrações de uma fracção para outra', 'answer' => 'Em primeiro lugar comunicar (presencialmente, com testemunhas, ou por carta registada com aviso de recepção) ao actual lesante (actual proprietário da fracção autónoma que apresenta defeitos, originadores de infiltrações) os direitos que lhe assistem relativamente ao vendedor, sugerindo que os exerça voluntariamente, acautelando assim os seus prejuízos derivados da obrigação de reparar os defeitos a expensas suas e/ou arriscando-se ainda a ter de indemnizar pelos danos causados. Se o condómino proprietário lesante estiver disposto a fazer valer rapidamente os seus direitos perante o anterior proprietário / vendedor, solicite que o mantenha informado das diligências adoptadas e dos resultados obtidos (que terão de conduzir inequivocamente à célere reparação dos defeitos). Caso contrário, resta-lhe responsabilizá-lo a ele (actual proprietário / comprador) pelas reparações indispensáveis e pelos danos causados, para o que antevejo necessariamente o recurso à via judicial.', 'pergunta_tipo_id' => 4],
            ['question' => 'Quotas em Atraso / Condómino que não paga', 'answer' => 'Independentemente dos motivos que os condóminos devedores invocam para não pagar, desde que haja uma deliberação em Acta da Reunião da Assembleia de Condóminos que delibere o montante das contribuições devidas ao condomínio ou quaisquer despesas necessárias à conservação e fruição das partes comuns e ao pagamento de serviços de interesse comum, devidamente aprovada e comunicada a todos os condóminos, sem ter sido impugnada, SÃO OBRIGADOS A PAGAR! (cf. art.ºs 1424.º, 1432.ºe 1433.º do Código Civil, conjugado com o art.º 6.º do Decreto-Lei n.º 268/94, de 25 de Outubro).', 'pergunta_tipo_id' => 4],
            ['question' => 'Acção de Despejo num Contrato de Arrendamento', 'answer' => 'Sempre que a lei exige o recurso a tribunal para fazer cessar o arrendamento, é necessária uma acção de despejo. Através da acção de despejo, o senhorio pretende que o tribunal declare a extinção do contrato de arrendamento e que condene o inquilino a desocupar a casa arrendada. Também é necessária acção de despejo quando o inquilino não aceite ou não execute o despedimento resultante de outra causa, como, por exemplo, se o inquilino acordou com o senhorio a cessação do arrendamento e depois se recusa a abandonar o prédio com os seus pertences. Durante a acção de despejo, o inquilino deve continuar a pagar ou a depositar a renda, porque, se o não fizer, o senhorio tem, em princípio, o direito de requerer o despejo imediato, sendo, no entanto, ouvido o inquilino.', 'pergunta_tipo_id' => 4],
            ['question' => 'De quem é a responsabilidade das obras que devem ser feitas numa varanda ?', 'answer' => 'De todos os condóminos, se as deficiências existirem no exterior da mesma, que constitui parte comum do prédio. Do condómino proprietário da fracção se o problema existir no interior da varanda (base da varanda).', 'pergunta_tipo_id' => 4],
            ['question' => 'Um cano a verter água fora da porta, entre o meu apartamento e o contador, quem tem a responsabilidade das obras?', 'answer' => 'Entre o contador e até á sua fracção (e dentro obviamente) é da sua responsabilidade. Do contador para fora e até à conduta de abastecimento a responsabilidade é do condomínio, daí para fora é do fornecedor de água (SMAS, Câmara Municipal, etc). ', 'pergunta_tipo_id' => 4],
            ['question' => 'Será legítimo o administrador efectuar as obras de reparação / conservação e apresentar a factura aos condóminos?', 'answer' => 'A administração das partes comuns do edifício compete à assembleia dos condóminos e a um administrador. (cf. artigo 1430.º, n.º 1, do Código Civil). Salvo disposição em contrário, as despesas necessárias à conservação e fruição das partes comuns do edifício e ao pagamento de serviços de interesse comum são pagas pelos condóminos em proporção do valor das suas fracções (expresso em percentagem ou permilagem, do valor total do prédio). (cf. artigo 1424.º, n.º 1, conjugado com o artigo 1418.º, n.º 1, ambos do Código Civil).', 'pergunta_tipo_id' => 4],
            ['question' => 'Quais são os requisitos importantes numa empresa de mudanças?', 'answer' => 'A existência de uma licença válida para transportar é uma das questões a colocar. Depois, procure saber referências. Pergunte que seguros fazem para cobertura da globalidade da carga e se é emitido um contrato, que é mesmo uma exigência legal. Pressupõe-se que os funcionários são profissionais de mudanças, mas pode sempre perguntar se são especializados.', 'pergunta_tipo_id' => 4],
            ['question' => 'Barulhos de fracções', 'answer' => 'Reclamação junto da Câmara Municipal;  O recurso, dado se falhe a reclamação, é alertar outras Entidades, nomeadamente o Ministério do Ambiente e o Governo Civil (embora este pouco possa fazer). Se não resultar, recorra aos Tribunais, solicitando uma providência cautelar para não arrastar por vários anos a decisão do processo. Claro que o Tribunal pode, se forem provados os factos, condenar os faltosos numa indemnização. Não é tarefa fácil, mas alguém tem de se impôr. Não deixe de consultar o Dec.-Lei 48/96 de 15 de Maio.', 'pergunta_tipo_id' => 4],
        ];

        foreach ($items as $item) {
            Pergunta::create($item);
        }
    }
}
