export const types = {
    FETCH_BLOCOS: 'FETCH_BLOCOS',
    FETCH_BLOCO_SELECTOR: 'FETCH_BLOCO_SELECTOR',
    FETCH_BLOCO: 'FETCH_BLOCO',
    CREATE_BLOCO: 'CREATE_BLOCO',
    UPDATE_BLOCO: 'UPDATE_BLOCO',
    DELETE_BLOCO: 'DELETE_BLOCO',
};