export const types = {
    FETCH_FRACAOS: 'FETCH_FRACAOS',
    FETCH_FRACAO: 'FETCH_FRACAO',
    UPDATE_FRACAO: 'UPDATE_FRACAO',
    UPDATE_FRACAOS: 'UPDATE_FRACAOS',


    RESET_CURRENT_FRACAOS: 'RESET_CURRENT_FRACAOS',
    SET_CURRENT_FRACAOS: 'SET_CURRENT_FRACAOS',
    FINISH_CURRENT_FRACAOS: 'FINISH_CURRENT_FRACAOS',
    FETCH_CURRENT_FRACAOS: 'FETCH_CURRENT_FRACAOS',
    FINISH_FETCH_CURRENT_FRACAOS: 'FINISH_FETCH_CURRENT_FRACAOS'
};